# Generated by Django 5.1.1 on 2024-10-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('list', models.CharField(max_length=15)),
                ('text', models.TextField(max_length=25)),
                ('cost', models.TextField(max_length=25)),
            ],
        ),
    ]
