# Generated by Django 5.1.2 on 2024-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ImageField(blank=True, null=True, upload_to='Calendars')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='CardIco')),
                ('title', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('list_1', models.CharField(blank=True, max_length=15, null=True)),
                ('list_2', models.CharField(blank=True, max_length=15, null=True)),
                ('list_3', models.CharField(blank=True, max_length=15, null=True)),
                ('text', models.CharField(blank=True, max_length=25, null=True)),
                ('cost', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.IntegerField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='Examples')),
                ('title_1', models.CharField(blank=True, max_length=300, null=True)),
                ('text_1', models.TextField(blank=True, max_length=300, null=True)),
                ('number_2', models.IntegerField()),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='Examples')),
                ('title_2', models.CharField(blank=True, max_length=300, null=True)),
                ('text_2', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ImageField(blank=True, null=True, upload_to='manual')),
                ('title_1', models.CharField(blank=True, max_length=50, null=True)),
                ('text_1', models.CharField(blank=True, max_length=200, null=True)),
                ('title_2', models.CharField(blank=True, max_length=50, null=True)),
                ('text_2', models.CharField(blank=True, max_length=200, null=True)),
                ('title_3', models.CharField(blank=True, max_length=50, null=True)),
                ('text_3', models.CharField(blank=True, max_length=200, null=True)),
                ('ico_1', models.ImageField(blank=True, null=True, upload_to='manual')),
                ('name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('description_1', models.CharField(blank=True, max_length=500, null=True)),
                ('ico_2', models.ImageField(blank=True, null=True, upload_to='manual')),
                ('name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('description_2', models.CharField(blank=True, max_length=500, null=True)),
                ('ico_3', models.ImageField(blank=True, null=True, upload_to='manual')),
                ('name_3', models.CharField(blank=True, max_length=50, null=True)),
                ('description_3', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Offer')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ImageField(blank=True, null=True, upload_to='Reviews')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle_1', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle_2', models.CharField(blank=True, max_length=50, null=True)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('cards', models.CharField(blank=True, max_length=50, null=True)),
                ('examples', models.CharField(blank=True, max_length=50, null=True)),
                ('offer', models.CharField(blank=True, max_length=50, null=True)),
                ('calendars', models.CharField(blank=True, max_length=50, null=True)),
                ('reviews', models.CharField(blank=True, max_length=50, null=True)),
                ('manual', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
