# Generated by Django 5.1.2 on 2024-10-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='is_active_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='example',
            name='is_active_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='number_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='number_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
