# Generated by Django 5.1.2 on 2024-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_setting_is_active_calendars_setting_is_active_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico_1', models.ImageField(blank=True, null=True, upload_to='manual')),
                ('name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('description_1', models.CharField(blank=True, max_length=500, null=True)),
                ('ico_2', models.ImageField(blank=True, null=True, upload_to='manual')),
                ('name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('description_2', models.CharField(blank=True, max_length=500, null=True)),
                ('ico_3', models.ImageField(blank=True, null=True, upload_to='manual')),
                ('name_3', models.CharField(blank=True, max_length=50, null=True)),
                ('description_3', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='manual',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='ico_1',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='ico_2',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='ico_3',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='name_3',
        ),
    ]
