# Generated by Django 5.1.2 on 2024-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_foot_remove_manual_description_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foot',
        ),
        migrations.AddField(
            model_name='manual',
            name='description_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='description_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='description_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='ico_1',
            field=models.ImageField(blank=True, null=True, upload_to='manual'),
        ),
        migrations.AddField(
            model_name='manual',
            name='ico_2',
            field=models.ImageField(blank=True, null=True, upload_to='manual'),
        ),
        migrations.AddField(
            model_name='manual',
            name='ico_3',
            field=models.ImageField(blank=True, null=True, upload_to='manual'),
        ),
        migrations.AddField(
            model_name='manual',
            name='name_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='name_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='name_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
