# Generated by Django 5.1.2 on 2024-10-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manual_number_1_manual_number_2_manual_number_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='list_1',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='list_2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='list_3',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
